name: (Mac) Build CPD-Multi-Client

on:
  workflow_dispatch:

jobs:
  build:
    name: (Mac) Build CPD-Multi-Client
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - run: python3 -m pip install setuptools

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Make and Publish
        run: npm run publish-mac
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
